### ISSUE TITLE
(BUG) can't turn on top monitors when ship got struck by lightning

### ISSUE THREAD

**Issue by TheComicRelief** [Shaosil/LethalCompanyMods-GeneralImprovements#177]
Getting the ship struck by lightning prevents you from turning the monitors back on except for the main big radar monitor. Quitting to main menu and re-entering doesn't fix it either. This happened when i used bettermonitors.

**Comment by Shaosil** [comment]
I _think_ the refactor that I just did in v1.2.7 should fix this so I'll close this issue. Ping me if it remains though.

**Comment by TheComicRelief** [comment]
@Shaosil Problem still persists unfortunately. Here's the code of the modpack i use 018f6c82-e2ae-81ac-ad17-104c1c522e15
